---
:install_cmd: apt-get install -y
:refresh_cmd: apt-get update
:upgrade_cmd: apt-get upgrade -y
:repo_url: http://leela.servidor/~general/repo/aula108
:remove_cmd: apt-get remove -y
:package_test_cmd: "dpkg -l <%= package_name %> |grep 'ii' | wc -l"  
:debug_option: false 
:verbose_option: true
:install_packages: true
:download_files: false
:process_commands: false
:configure_users: true
:room: aula108
